function cp = myappjcp()
    % myappcjp returns the javaclasspath for this
    listing = dir( fullfile( ...
        myapproot(), ...
        'jar', ...
        '*.jar' ) );
    listing = arrayfun( @(jar) fullfile( jar.folder, jar.name ), ...
        listing, ...
        'UniformOutput', false );
    cp = strjoin( listing, ';' );
end
